import { useState, useMemo, useCallback, useRef } from "react";
const G="#D4A853",Gd="#8B7335",Gf="#5A4D2E",BG="#0D0C0A",SF="#141210",BD="#252117";
const CS=["Forgiveness","Deen & Sincerity","Protection","Speech & Confidence","Character & Discipline","Career & Building","Wealth & Provision","Marriage & Family","Health & Fitness","Dream Life & Legacy","Ummah & Justice","Worldview & Consciousness","Akhirah"];
const HT=[
{t:"The Core Tension",q:"Where am I still split between dunya and akhirah?",c:"You do not want a shallow life. You want dunya — but not empty dunya. You want success, money, beauty, strong work, a good home, meaningful projects, a family, and a respected life — but you want all of it to be clean, halal, sincere, and worth something in front of Allah. You carry a constant tension between wanting to build and win in the world, and fearing becoming distracted, ego-driven, numb, performative, or spiritually hollow. This is not a weakness. This tension is your compass. The day you stop feeling it is the day you should worry."},
{t:"Sincerity in Worship",q:"Is my worship changing me, or just checking a box?",c:"You want the real thing — closeness to Allah, obedience, consistency, humility, and acceptance. You fear your salah becoming robotic, your deen becoming identity without substance, and your worship becoming performance. You don't want to be someone who posts Islamic quotes but doesn't pray on time. You don't want to look religious without being transformed by religion. You want worship that rewires your character — that makes you more patient in traffic, more honest in business, more gentle with your wife, more humble in success."},
{t:"Fear of Wasted Potential",q:"Am I becoming who I was supposed to become?",c:"You fear dying while attached to dunya. You fear arriving on the Day of Judgment with a life that looked productive but lacked depth. You fear being capable of more but failing to act — paralyzed by overthinking, scattered by distractions, delayed by comfort. You fear being swallowed by modern habits and noise — endless scrolling, passive consumption, dopamine loops. You fear leaving behind potential instead of impact. You fear that the gap between who you are and who you could be will be the thing you regret most when it's too late to close it."},
{t:"Building with Purpose",q:"Does my work serve something greater than my bank account?",c:"A huge part of you wants to build — not just have a job. Build. You want work that is independent, scalable, ethical, intelligent, creative, useful, respected, and financially meaningful. You hate sketchy practices. You want to make money in a way that feels principled — halal in source, barakah in outcome. You want Sahara Delights, Hibachi Blue, Ek Cup Chai, MazayKaMatcha to be more than businesses. You want them to be contributions. Products that nourish, experiences that elevate, brands that carry meaning. You want to look at your work and know it reflects something true about you."},
{t:"Confidence & Speech",q:"When was the last time I said exactly what I meant?",c:"You struggle with confidence, especially when speaking and expressing your thoughts. You fear being disliked, fear sounding argumentative, shut down when intimidated, soften your words too much, use filler words, circle around the point instead of landing on it. But inside you, there is a person with clear, sharp, grounded thoughts — someone who knows exactly what he thinks. The gap between your inner clarity and your outer expression is where the frustration lives. You want speech that is firm but gracious, confident but humble, precise but warm. You want to be someone whose words carry weight."},
{t:"The Ideal Life",q:"What would it look like if everything aligned?",c:"A life of beauty, peace, barakah, control, dignity, and meaningful work. A thoughtfully designed home — calm, ordered, elegant, filled with warmth and personality. Physical spaces with natural light, good materials, and intentional objects. Enough wealth to feel free and generous — to give without counting, to support your parents, to invest without anxiety. Strong family life. Good health and energy. Creative work that is respected and aligned with your values. Less dependence on broken systems. The freedom to choose your life, not just react to it. Not random luxury — thoughtful luxury. Beauty with meaning. Comfort with restraint. Elegance with soul."},
{t:"Marriage & Legacy",q:"What kind of home am I building — not the structure, but the spirit?",c:"You want love with mercy, softness, and emotional safety. You want a marriage that is not transactional or functional but deeply connected — where vulnerability is safe, where growth is mutual, where both of you are becoming better versions of yourselves together. You want a peaceful home rooted in deen and warmth. Righteous children who love Allah without being forced. Leading without harshness. Providing well. Being emotionally present, not just physically there. You want to take care of your parents — honoring the sacrifices they made, making them proud. You want to build a lineage that is better, stronger, and more conscious than what came before."},
{t:"Justice & the Ummah",q:"What am I doing with my comfort while others have none?",c:"Grief over Palestine sits heavy in your heart. Concern for the oppressed in Sudan, Congo, and every forgotten corner where Muslims bleed without headlines. You feel the frustration of watching systems of power operate unchecked — propaganda twisting truth, media erasing victims, the world scrolling past genocide and returning to entertainment. You want your success to serve more than just yourself. You want your money, your platform, your voice to mean something for the Ummah. You don't want to be comfortable while your brothers and sisters have no comfort at all. You don't want to become numb. Numbness is the real danger."},
{t:"Discipline & Character",q:"What would my life look like if I actually executed what I already know?",c:"You care deeply about discipline but feel frustrated with scattered attention, inconsistency, delay, overthinking, and the painful gap between what you know and what you execute. You know what to do — you just don't always do it. You want honorable presence without arrogance. Patience in relationships, in business, in personal growth, in waiting on Allah's timing. You want to be the kind of man who follows through — who says he'll do something and does it, who starts something and finishes it, who shows up the same way on day 100 as day 1. You want your character to match your ambition."},
{t:"The Deepest Hope",q:"If Allah granted everything in your heart right now — what would it look like?",c:"Allah is pleased with you. Your life has barakah — not just money, but meaning in every corner. Your work benefits people and is counted as good. Your home is peaceful and full of mercy. Your marriage deepens in love, respect, and tranquility with every passing year. Your children are righteous and beautiful in character — they love their deen, they honor their parents, they make the world better. You become more disciplined, focused, and clear. Your speech becomes strong and sincere. Your wealth is halal, expansive, and generous. You build something real and lasting. You live with integrity. You die in a state that Allah loves. You enter Jannatul Firdaus by His mercy — with your family beside you, forever."},
];
const D=[
[0,"Allah","God","Akhirah","The greatest Name encompassing all attributes — the one and only deity worthy of worship.","Ya Allah, I ask You by every Name You have named Yourself, and by every Name hidden in the knowledge of the unseen, to make the end of my life the best of it, and the best of my days the day I meet You. Ya Allah, let me not be someone who built in this world but arrived bankrupt in the next. Let me not be someone whose businesses grew while his soul shrank. Let my final breath be one of iman, my grave a garden from the gardens of Jannah, and my destination Jannatul Firdaus — not because I earned it, but because Your mercy carried me."],
[1,"Ar-Rahman","The All-Compassionate","Marriage & Family","His mercy is vast and universal — extending to every creature. The womb (rahim) derives from the same root.","Ya Rahman, Your compassion covers everything in creation. Cover my marriage with that same compassion. Let mercy be the foundation of our home — not ego, not scorekeeping, not frustration. Make me a husband whose compassion mirrors the standard You set: patient when she is tired, gentle when she is emotional, steady when things are hard. And bless my parents with comfort and joy. They sacrificed for me. Let me honor those sacrifices with a life that makes them proud and a home that brings them peace."],
[2,"Ar-Raheem","The Most Merciful","Marriage & Family","His special, intimate mercy reserved for believers — guiding back when you stray, softening hearts.","Ya Raheem, show me Your special mercy in my family life. Be merciful in how my marriage grows — through the growing pains, the misunderstandings, the seasons where we’re both stretched thin. Let mercy be the language of our household. And when we have children, ya Raheem, let them be born into mercy — raised with softness and strength, connected to their deen, and surrounded by love that is rooted in Your mercy, not in the world’s dysfunction."],
[3,"Al-Malik","The King","Dream Life & Legacy","The absolute ruler whose sovereignty is total and eternal. Everything you possess belongs to Him.","Ya Malik, You own everything, and what I’m asking for is a portion of Your kingdom — a beautiful home, a peaceful life, a successful business, a strong body, a righteous family. Grant me a life that feels intentional rather than chaotic. A life where I chose how I live instead of reacting to circumstances. A life of dignity, freedom, and barakah. I don’t want a flashy life — I want a life of beauty with meaning, comfort with restraint, and elegance with soul."],
[4,"Al-Quddus","The Most Holy","Deen & Sincerity","Absolutely pure — free from every flaw. Only the Pure can purify.","Ya Quddus, purify my worship. I don’t want my salah to be robotic — something I check off a list while my mind is running through ad campaigns and fulfillment orders. I want salah that changes me, that resets me, that connects me to You. Purify my intentions in everything — in my business, in my charity, in my du’as. Remove the parts of my worship that are for show and leave only what is for You. I am terrified of spiritual performance without spiritual substance."],
[5,"As-Salam","The Source of Peace","Protection","The origin of all peace and security. Peace is found in proximity to Him.","Ya Salam, grant me peace — real peace, not the fake peace of numbing myself with content and consumption. Peace in my home, peace in my marriage, peace in my mind when it races at night with business ideas and anxieties. Protect me from inner chaos, from the noise of comparison, from the restlessness that comes from wanting more before appreciating what I have. Let my life feel calm, ordered, and grounded — even when things are uncertain."],
[6,"Al-Mu'min","The Inspirer of Faith","Deen & Sincerity","He grants security, confirms truth, and inspires faith.","Ya Mu’min, strengthen my iman when it dips. There are days when I feel fire for my deen and days when I feel numb. Protect me from the numbness. Let my faith not be seasonal or emotional but steady and rooted. When the world normalizes what is haram, when dominant ideologies make Islam look strange, when social media flattens everything sacred into content — keep my iman unshaken. Inspire faith in me that is deep enough to survive doubt, pressure, and isolation."],
[7,"Al-Muhaymin","The Guardian","Protection","He watches over all things with complete authority. Nothing escapes His care.","Ya Muhaymin, guard my heart from becoming attached to status, brand perception, follower counts, or revenue milestones in a way that makes me forget why I started. Guard my family from harm I cannot see. Guard my businesses from the evil eye of those who watch but do not wish well. Guard my marriage from the erosion that comes from stress, busyness, and emotional distance. Be the Guardian over everything I love, because I cannot protect it all on my own."],
[8,"Al-Aziz","The Almighty","Ummah & Justice","All might paired with wisdom. Every empire that oppressed crumbled before Him.","Ya Aziz, You are the Almighty, and the oppressors of this world are nothing before You. Grant victory and honor to the people of Palestine. Strengthen the Muslims of Sudan, Congo, and every land where our brothers and sisters are suffering. They are being bombed, starved, displaced, and silenced — and the world watches while normalizing their pain. Show Your might. Break the systems that profit from their suffering. And do not let me become numb to their pain while I sit comfortably planning product launches."],
[9,"Al-Jabbar","The Restorer","Ummah & Justice","He compels creation to His will and mends what is broken. 'Jabr' means to set a broken bone.","Ya Jabbar, You are the Restorer of the broken. Restore Palestine. Restore the homes destroyed, the families torn apart, the childhoods stolen. Restore the dignity of every Muslim who has been humiliated by oppression. And restore my own heart from the cynicism that grows when I watch injustice continue unchecked. Don’t let me become someone who cares only about his own life while the Ummah bleeds. Compel the oppressors to face Your justice, and mend what they have shattered."],
[10,"Al-Mutakabbir","The Supreme","Character & Discipline","All greatness belongs exclusively to Him. Pride is His garment alone.","Ya Mutakabbir, greatness belongs only to You, and I ask You to strip away any arrogance growing in me that I haven’t caught yet. I want to be confident, not cocky. I want honorable presence, not vanity. When my businesses succeed, when my products are praised, when people respect my work — don’t let it go to my head. Keep me grounded. The moment I start feeling superior to anyone, humble me gently before You humble me publicly."],
[11,"Al-Khaliq","The Creator","Career & Building","He brought everything from nothing. Your ability to create is borrowed light.","Ya Khaliq, You created everything from nothing, and I want to create with that same spirit — bringing something meaningful into the world where nothing existed before. You gave me the mind to build Sahara Delights from a kitchen idea into a real brand, to envision Hibachi Blue, to dream up Ek Cup Chai and MazayKaMatcha. Let my creations carry Your barakah. Let them be more than products — let them be contributions. And never let me forget that my ability to create is borrowed from You, the original Creator."],
[12,"Al-Bari'","The Originator","Career & Building","He creates all beings with distinct form, free from prior model.","Ya Bari’, You brought life into existence with no blueprint. I am trying to do the same in my own small way — building concepts that don’t have a clear template, carving out space in industries that weren’t designed for someone like me. Give me the courage to originate, not just imitate. Let my brands be distinct. Let Sahara Delights reflect something that no other confectionery brand does — the story of Jericho, the craft, the intention. Let my work be unmistakably mine and unmistakably blessed by You."],
[13,"Al-Musawwir","The Fashioner","Career & Building","The divine Designer. Your eye for beauty traces back to Him.","Ya Musawwir, You shape every creation with beauty and purpose. I care about aesthetics — in my packaging, in my menus, in my product presentation, in my pop-up displays. But let my sense of design come from You, not just from trends. Shape my taste so that my products are beautiful with meaning, elegant with soul. When I design a label for the Crown Core collection or a layout for Hibachi Blue’s menu, let it be thoughtful, refined, and honest. Let form and function meet in everything I make."],
[14,"Al-Ghaffar","The Repeatedly Forgiving","Forgiveness","He forgives again and again with no limit. The door is never locked.","Ya Ghaffar, I keep falling short and You keep the door open. I keep returning to the same weaknesses — the procrastination, the inconsistency, the distractions, the moments of spiritual laziness — and You keep forgiving. Forgive me again. Forgive me for the sins I committed knowingly and the ones I committed in ignorance. Forgive me for the times I prioritized appearance over substance. Forgive me for a life partially fragmented by modern noise and scattered focus. And do not let my familiarity with Your mercy make me careless with Your boundaries."],
[15,"Al-Qahhar","The Subduer","Ummah & Justice","He prevails with irresistible power. Every tyrant is subdued before Him.","Ya Qahhar, subdue every tyrant who bombs children, blockades aid, and profits from the starvation of innocent people. Subdue the propaganda machines that twist truth and erase suffering. Subdue the norms that make people scroll past genocide and return to entertainment. And subdue the part of my nafs that wants to look away because the pain is too heavy to carry. Don’t let me become comfortable with oppression. Keep me disturbed, and let that disturbance move me to action."],
[16,"Al-Wahhab","The Bestower","Wealth & Provision","He gives abundantly, freely, without expecting return.","Ya Wahhab, You give without being asked and without expecting return. Bestow upon me wealth that is clean — halal in how I earn it, barakah in how I spend it, and generosity in how I share it. I don’t want scammy money. I don’t want income that makes me compromise my principles. Bestow upon me the kind of wealth that lets me take care of my parents, support my wife, give without fear, invest wisely, and still sleep peacefully at night knowing every dollar was earned with dignity."],
[17,"Ar-Razzaq","The Provider","Wealth & Provision","The ultimate Provider. He provides before you ask, through doors you didn't knock on.","Ya Razzaq, You provide for the ant inside the rock and the bird that leaves its nest with an empty stomach and returns full. Provide for me in ways I haven’t even imagined. Open doors of rizq that I didn’t knock on. Bring customers to my products, bring opportunities to my inbox, bring partnerships that multiply what I’ve built. And provide for me spiritually too — sustain my iman, sustain my energy, sustain my hope when the numbers are slow and the doubts are loud."],
[18,"Al-Fattah","The Opener","Speech & Confidence","He opens what is closed — doors of mercy, provision, tongues.","Ya Fattah, open my tongue. I struggle to say what I mean with force and clarity. I hedge, I soften, I use filler words, I circle around the point instead of landing on it. Open the doors of eloquence for me. Open my ability to communicate vision — to investors, to customers, to my family, to anyone who needs to understand what I’m building and why. And open my mouth in Your remembrance so that the most powerful words I speak are the ones I speak to You."],
[19,"Al-'Aleem","The All-Knowing","Worldview & Consciousness","His knowledge encompasses everything. Every human ideology is partial before Him.","Ya ’Aleem, You know the truth behind every narrative, every headline, every cultural norm. Give me knowledge that cuts through propaganda, trend, and noise. I live in a time where constant information erodes clarity instead of building it. Give me the kind of knowledge that is rooted in revelation, tested by experience, and guided by wisdom. Let me not be someone who absorbs norms without questioning them. Let me know the truth and have the courage to live by it."],
[20,"Al-Qabid","The Restrainer","Worldview & Consciousness","He constricts by wisdom. Sometimes tightness is a divine redirect.","Ya Qabid, restrain me from consuming what is not good for me — content that wastes my time, ideas that confuse my values, habits that dull my sensitivity to You. Restrain my appetite for dopamine, for endless scrolling, for the quick hit of engagement that masquerades as productivity. Tighten my world when it needs tightening. Sometimes constriction is Your mercy — and I trust that when You withhold, You are teaching me to need less from the world and more from You."],
[21,"Al-Basit","The Expander","Speech & Confidence","He expands provision, hearts, and confidence. Your capacity for expression is not fixed.","Ya Basit, expand my confidence. I shrink in rooms where I should stand tall. I swallow my words when I should speak clearly. I dim my presence when I should let it fill the room. Expand my chest, ease my anxiety, and give me the inner spaciousness to speak without fear. Expand not just my speech but my capacity to be seen, heard, and respected — not for ego, but because the work I am doing deserves a voice that matches its value."],
[22,"Al-Khafid","The Humbler","Character & Discipline","He lowers whoever He wills. Ask to be humbled gently in private.","Ya Khafid, humble me in private so You don’t have to humble me in public. I know ego is one of my biggest threats — it shows up subtly, in how I compare myself to others, in how I want to be seen, in the quiet satisfaction I feel when I outperform someone. Humble me before it becomes a disease. And protect me from the humiliation that comes from ignoring Your reminders. I would rather be humbled by my own reflection than humbled by a fall."],
[23,"Ar-Rafi'","The Exalter","Character & Discipline","He raises in rank and honor. True elevation comes from Him alone.","Ya Rafi’, elevate me in the ways that matter. Not just in revenue or social status — but in Your sight. Raise my rank in akhirah. Raise my character. Raise my patience. Raise my discipline. And if it is Your will, raise my name in this world too — but only in a way that serves You and benefits others. Let me be elevated for what I contribute, not for what I consume. And never let me be raised in dunya while I’m sinking in akhirah."],
[24,"Al-Mu'izz","The Giver of Honor","Character & Discipline","True honor comes from Allah alone.","Ya Mu’izz, the only honor that is real is what comes from You. I have chased validation from people — from clients, from social media, from family expectations — and it never satisfies. Grant me the honor that comes from obeying You when it’s hard, from speaking truth when it’s unpopular, from building something halal when haram shortcuts are everywhere. Honor me through my deen, and let that be enough. Let me never seek honor by compromising what I believe."],
[25,"Al-Mudhill","Giver of Disgrace","Character & Discipline","He strips honor from whoever persists in arrogance or hypocrisy.","Ya Mudhill, I seek refuge in You from disgrace — the disgrace of being exposed for hypocrisy, the disgrace of building an image that doesn’t match my reality, the disgrace of being successful in public and empty in private. Don’t let me become someone who is disgraced for arrogance, dishonesty, or spiritual fraud. If I am heading toward disgrace without knowing it, stop me. Redirect me. Break my ego before You break my reputation."],
[26,"As-Samee'","The All-Hearing","Speech & Confidence","He hears every whispered du'a, every cry, every unspoken thought.","Ya Samee’, You hear every word I say and every word I swallow. You hear the thoughts I’m too afraid to speak and the du’as I make when no one else is listening. Since You hear me perfectly, help me be someone who speaks with precision, not someone who rambles and over-explains. Make my words count. And when I speak truth that others don’t want to hear, give me the courage to say it anyway — knowing You heard me, even if no one else validates it."],
[27,"Al-Baseer","The All-Seeing","Worldview & Consciousness","He sees everything — the tears you cry alone, the sincerity behind the struggle.","Ya Baseer, You see what the world refuses to see — the suffering behind the statistics, the corruption behind the institutions, the emptiness behind the influencer lifestyles. Open my eyes to what matters and close them to what distracts. Let me see clearly enough to build with purpose, parent with wisdom, speak with clarity, and live without delusion. And let me see my own self clearly — my real strengths, my real weaknesses, and the real state of my heart before You."],
[28,"Al-Hakam","The Judge","Ummah & Justice","The ultimate Judge whose verdict is final.","Ya Hakam, You are the ultimate Judge, and on the Day of Judgment, every oppressor will stand before You with no army, no propaganda, no media spin, and no allies. Judge them with Your justice. And judge me too — for my silence when I should have spoken, for my comfort when I should have sacrificed, for my distance from causes that deserved my attention and resources. Let me not arrive before You having lived only for myself."],
[29,"Al-'Adl","The Just","Ummah & Justice","Perfect justice. He does not wrong anyone by an atom's weight.","Ya ‘Adl, I believe in Your justice even when the world’s courts fail. Even when the UN is useless. Even when sanctions never come. Even when the news cycle moves on. Your justice is final and it is coming. Grant justice to the people of Palestine, of Sudan, of Congo, of every land where Muslims are oppressed. And make me an instrument of justice in whatever way I can — through my money, my voice, my platform, my du’as, and my refusal to be silent."],
[30,"Al-Lateef","The Subtle","Marriage & Family","His kindness reaches you through invisible pathways.","Ya Lateef, work in my life in ways I cannot see. Place hidden blessings in my marriage — small moments of connection that prevent bigger cracks from forming. Place subtle protection around my family from harm I’m not aware of. Guide my wife and me toward each other in ways that feel natural, not forced. You are the One who arranges things behind the scenes with a gentleness that we don’t notice until we look back and say, “That was You.” Keep being gentle with us."],
[31,"Al-Khabeer","The All-Aware","Worldview & Consciousness","He knows the inner reality of everything — every hidden motive.","Ya Khabeer, You know the full context — of every society, every ideology, every cultural shift. I live in a world that rewards speed, trends, and appearance over truth, meaning, and depth. Make me aware of the traps I don’t see — the traps of cultural assimilation that erode Islamic identity, the traps of productivity culture that make rest feel sinful, the traps of hustle content that glorifies burnout. Keep me aware, keep me conscious, keep me thinking — because the moment I stop thinking, I start conforming."],
[32,"Al-Haleem","The Forbearing","Forgiveness","He does not rush to punish. Supreme power restrained by supreme mercy.","Ya Haleem, You do not rush to punish me even when I deserve it. You gave me time when I wasted time. You gave me another morning when I did nothing worthy of the night before. You held back consequences so I could come back to You. I do not deserve Your patience, but I desperately need it. Keep being forbearing with me while I try to become better — more consistent, more disciplined, more sincere. Don’t give up on me the way I sometimes give up on myself."],
[33,"Al-'Adheem","The Magnificent","Character & Discipline","Incomprehensible greatness. When you feel His greatness, human opinions become very small.","Ya ’Adheem, make me someone who is in awe of Your greatness — so deeply that the opinions of people become small. My people-pleasing, my fear of being disliked, my tendency to soften my words too much — all of it comes from caring too much about what people think and not enough about what You think. Fill me with such awareness of Your magnificence that human approval loses its grip on me. Let my primary audience be You."],
[34,"Al-Ghafoor","The All-Forgiving","Forgiveness","He covers sins completely. Your past does not define your future.","Ya Ghafoor, don’t just forgive my sins — cover them. Conceal the embarrassing things, the shameful things, the moments I would never want anyone to know. I carry regret over wasted potential, over seasons of my life where I knew what to do but didn’t act. I carry guilt over arrogance I didn’t catch in time, over words I said without thinking, over prayers I rushed through. Erase it all. Not because I am worthy but because You are Al-Ghafoor and that is who You are."],
[35,"Ash-Shakoor","The Appreciative","Deen & Sincerity","He multiplies the smallest good deeds. Nothing is too small.","Ya Shakoor, I have not done enough, but You multiply the little I bring. Appreciate the small things I do for Your sake — the du’as I whisper in the car, the moments I hold myself back from haram, the small choices I make to choose You over convenience. If You appreciate my small worship, it gives me hope that I can grow. Don’t let me belittle the little I do, and don’t let me be satisfied with it either. Let gratitude and ambition live side by side in my heart."],
[36,"Al-'Aliyy","The Most High","Dream Life & Legacy","Above all creation. Stop placing money or opinions on pedestals.","Ya ’Aliyy, elevate the quality of my life — not in a materialistic way, but in a way that reflects Your favor. Let my standard of living rise because my standard of worship rose first. Let my environment reflect my values — clean, ordered, minimal, warm, inspiring. Let me build spaces that feel premium and intentional. I want the kind of life where every detail — from the food on my table to the furniture in my home to the clothes on my body — speaks of someone who lives with thought and purpose."],
[37,"Al-Kabeer","The Most Great","Dream Life & Legacy","He didn't give you ambition just to live on autopilot.","Ya Kabeer, don’t let me settle for a small life. I was born with a double bachelor’s and a master’s degree, multiple business ideas, creative energy, and a deep spiritual hunger. You did not wire me this way just to live a mediocre existence. Give me the courage to live at the scale of the potential You placed inside me. Let me think bigger, build bigger, and dream bigger — while staying rooted in humility and worship of You, the truly Great One."],
[38,"Al-Hafeez","The Preserver","Protection","He is holding it all in place when everything feels fragile.","Ya Hafeez, preserve my iman when life gets busy and worship slips. Preserve my marriage from the subtle damage of neglect. Preserve my health from what I can’t see coming. Preserve Sahara Delights and everything I’ve built from collapse, from bad partnerships, and from financial ruin. Preserve the good in me — the sensitivity, the depth, the desire for meaning — and don’t let the harshness of the world strip it away. Preserve my sincerity most of all, because without it, everything else is hollow."],
[39,"Al-Muqeet","The Nourisher","Wealth & Provision","He nourishes the seed underground before it breaks soil.","Ya Muqeet, nourish my businesses the way You nourish every living thing. Sahara Delights needs nourishment — consistent orders, growing brand awareness, operational stability, loyal customers. Nourish it. Ek Cup Chai and MazayKaMatcha need nourishment — the right events, the right crowds, the right word of mouth. Nourish them. Hibachi Blue needs nourishment — clarity in concept, the right location, the right launch timing. Nourish it. And nourish me — the founder behind all of it — with energy, clarity, and barakah."],
[40,"Al-Haseeb","The Reckoner","Worldview & Consciousness","Both accountability and sufficiency.","Ya Haseeb, You will reckon every moment I was given and how I used it. Reckon me gently — but reckon me honestly. I fear showing up on the Day of Judgment with a life that was full of activity but empty of purpose. A life where I was busy but not intentional. Where I posted content but didn’t study my deen. Where I optimized conversion rates but didn’t optimize my salah. Let the reckoning push me to be more intentional today — not tomorrow, today."],
[41,"Al-Jaleel","The Majestic","Speech & Confidence","Presence that commands awe without a word.","Ya Jaleel, give me the kind of presence that commands respect without arrogance. Not loudness — presence. Not dominance — gravity. When I walk into a room, a meeting, or a pitch, let me carry the composure of someone who knows who he is and Whose he is. Let my demeanor reflect thoughtfulness, not insecurity. Let my speech reflect certainty, not desperation. Grant me a majestic presence that is rooted in humility before You and confidence in the purpose You gave me."],
[42,"Al-Kareem","The Most Generous","Wealth & Provision","He gives before you ask, more than you deserve. He cannot not give.","Ya Kareem, You give without measure and without condition. Be generous with me in provision, in opportunity, in barakah, and in ease. Be generous in how You open doors for my businesses. Be generous in sending me customers who love what I make. Be generous in granting me financial freedom so I can stop worrying about scarcity and start thinking about legacy. And make me generous too — with my money, my time, my knowledge, and my service to the Ummah."],
[43,"Ar-Raqeeb","The Watchful","Protection","He watches for accountability through ihsan, not punishment.","Ya Raqeeb, You watch everything. You see when I open my phone with the intention to work and end up wasting an hour. You see when I tell myself I’ll pray in five minutes and let twenty pass. You see the gap between who I present myself as and who I actually am. Let the awareness of Your watching make me more honest — not anxious, but accountable. Let me live as though You are watching, because You are."],
[44,"Al-Mujeeb","The Responsive","Marriage & Family","He answers every call — sometimes differently than expected.","Ya Mujeeb, respond to the du’as I’ve been making in silence — for a beautiful home, for righteous children, for a marriage that deepens in love and emotional safety, for parents who live long enough to see the fruit of everything they planted in me. I’ve been asking for these things for a long time. I know You answer — sometimes with what I asked for, sometimes with something better, sometimes by protecting me from what I wanted. Whatever form Your response takes, let me recognize it and accept it with gratitude."],
[45,"Al-Wasi'","The Vast","Wealth & Provision","His provision has no ceiling. What He set aside for you cannot be taken.","Ya Wasi’, Your provision is vast enough for everyone. Remove the scarcity mindset from my heart. I sometimes operate from anxiety — afraid there isn’t enough money, enough customers, enough time, enough opportunity. But You are vast. Expand my belief in what is possible. Let me stop thinking small and start building with the confidence that Your rizq has no ceiling. What You have destined for me cannot be taken by anyone else."],
[46,"Al-Hakeem","The All-Wise","Character & Discipline","Everything with perfect wisdom. Every delay has a purpose.","Ya Hakeem, give me wisdom to match my ambition. I have ideas, energy, and drive — but without wisdom, all of that becomes scattered force. Give me the wisdom to know when to speak and when to be silent, when to push forward and when to wait, when to invest and when to hold, when to fight for my vision and when to surrender to Yours. Teach me the wisdom of pacing, of patience, of trusting Your timing over my urgency."],
[47,"Al-Wadud","The Most Loving","Deen & Sincerity","He loves deeply, actively, personally.","Ya Wadud, I want You to love me. Not just tolerate me or be patient with me — but love me. I want to be among the ones You are pleased with. I want to feel closeness to You, not just obligation. I want my obedience to come from love, not fear alone. Make me someone You love by making me someone who loves what You love — truth, justice, sincerity, humility, patience, and worship that is alive. And let me feel Your love in the barakah of my life, the peace in my home, and the clarity in my heart."],
[48,"Al-Majeed","The All-Glorious","Speech & Confidence","Supreme glory with supreme generosity. The right thing at the right time.","Ya Majeed, let my words carry weight. I admire speech that is thoughtful, sharp, grounded — not performative, not weak, not unnecessarily blunt. Make my speech reflect that ideal. When I explain Sahara Delights’ mission, when I pitch Hibachi Blue, when I talk about my vision — let my words land with clarity and glory. Let people listen not because I’m loud but because what I’m saying is worth hearing. Remove the stuttering, the hedging, the filler. Replace it with firmness and grace."],
[49,"Al-Ba'ith","The Resurrector","Akhirah","He will raise every soul. What will you be raised with?","Ya Ba’ith, You will raise me from the dust and I will stand before You with everything exposed — every intention I buried, every sin I thought no one saw, every day I wasted scrolling when I should have been building or praying. When You resurrect me, let me rise among the righteous. Let me not be raised with the distracted, the spiritually lazy, or the people who had every gift but squandered them. Let my resurrection be the beginning of eternal relief, not eternal regret."],
[50,"Ash-Shaheed","The Witness","Akhirah","He witnesses all things. For the one who feels unseen — nothing was wasted.","Ya Shaheed, You witnessed every night I stayed up making du’a and every night I stayed up doing nothing of value. You witnessed every moment I chose You and every moment I chose my nafs. You witnessed the tears no one saw and the sins no one knew. On the Day when witnesses are called, be my witness that I tried — imperfectly, inconsistently, sometimes weakly — but I tried to turn back to You. Let the record You witnessed testify in my favor by Your mercy."],
[51,"Al-Haqq","The Truth","Akhirah","The absolute Truth. Build on truth and it stands forever.","Ya Haqq, when everything false falls away on the Day of Judgment — the status, the followers, the image, the brand perception — let what remains of me be true. I fear living a life that looked productive outwardly but lacked depth inwardly. I fear arriving before You with a résumé of accomplishments but a heart that was hollow. Make me true in my worship, true in my work, true in my speech, and true in my love for You — so that when the Truth is all that remains, I am not exposed as someone who was living a lie."],
[52,"Al-Wakeel","The Trustee","Career & Building","The spreadsheet is yours. The outcome is His.","Ya Wakeel, I hand my businesses over to You. I’ve done the spreadsheets, run the ads, analyzed the Meta campaigns, built the fulfillment tools, sourced the ingredients, and designed the inserts. But after the effort, the outcome is Yours. Be the disposer of my affairs. When partnerships don’t work out, when sales are slow, when Shopify glitches and DNS records don’t authenticate — handle what I cannot. I trust You with the results even when the results don’t match my projections."],
[53,"Al-Qawiyy","The All-Strong","Health & Fitness","Absolute strength that never diminishes.","Ya Qawiyy, grant me physical strength that supports my ambitions. I need a body that can handle the demands of building multiple businesses, staying present in my marriage, worshipping You with energy, and showing up consistently for the people who depend on me. Make me strong — not for vanity, but for function. Let my body reflect the discipline I want in every other area of my life. Remove the sluggishness. Replace it with energy, stamina, and capability."],
[54,"Al-Mateen","The Steadfast","Health & Fitness","Firm, unwavering. Consistency is a gift from the eternally consistent.","Ya Mateen, make my health firm and steadfast. I don’t want to crash and burn — I want sustained energy, not bursts followed by burnout. Make my fitness habits consistent, not seasonal. Let me show up at the gym, eat well, sleep well, and care for my body with the same firmness I want in my character. My body is an amanah from You. Help me treat it like one — not abusing it with junk, neglect, or laziness, but maintaining it with respect."],
[55,"Al-Waliyy","The Protecting Friend","Protection","The close ally of believers. More invested in your success than you are.","Ya Waliyy, I need a protector I can truly depend on. Be my ally when the world feels competitive and isolating. Be the friend who supports me when I feel unseen, overlooked, or underestimated. Protect me from bad company — from people who normalize mediocrity, people who drain my ambition, people who subtly pull me away from You. Surround me instead with people who sharpen my deen and my drive."],
[56,"Al-Hameed","The All-Praiseworthy","Speech & Confidence","The most powerful thing you can say is praise of Him.","Ya Hameed, make me someone whose speech praises You naturally — not performatively, but from genuine overflowing gratitude. When people ask me about my success, let my first instinct be to credit You. When I write copy, create content, or craft a brand message, let there be an undercurrent of truth and goodness in my words. And make my tongue an instrument of praise in private — in my salah, in my dhikr, in the quiet moments — not just in public where people can see."],
[57,"Al-Muhsi","The Accounter","Health & Fitness","He counts everything. Your effort matters. Every rep counts.","Ya Muhsi, You count everything — every calorie, every step, every heartbeat, every cell. Help me be intentional about what I put into my body. Help me count in the right ways — tracking my fitness, tracking my nutrition, building sustainable routines. And beyond the physical, let me be accountable for how I use the body You gave me. Am I using it for worship? For productivity? For service? Or am I wasting it on the couch, drained by screens and empty habits?"],
[58,"Al-Mubdi'","The Originator","Career & Building","He creates from nothing. If the idea is in your heart, originate it.","Ya Mubdi’, You originated this entire universe. Bless me with original ideas — products, concepts, brand experiences, and business models that haven’t been done before. Don’t let me be a copycat entrepreneur. Let me originate things that make people pause and say, “This is different.” Whether it’s a new flavor in the Gourmet collection, a new pop-up concept, or a completely new venture — let originality flow from my mind because You inspired it."],
[59,"Al-Mu'id","The Restorer","Career & Building","Nothing is permanently lost. The dream that died can be resurrected.","Ya Mu’id, restore what has been lost in my entrepreneurial journey. Restore the time I feel I wasted before getting serious. Restore the confidence I lost after setbacks. Restore the momentum that slowed when life got complicated. And if there are businesses or ideas I shelved too early — restore them if they are good for me, or replace them with something better. You are the One who brings things back to life, and I am asking You to revive what deserves to be revived."],
[60,"Al-Muhyi","The Giver of Life","Marriage & Family","He makes dead things live again.","Ya Muhyi, when the time is right, bless my marriage with children — righteous, healthy, beautiful in character, and connected to You from their first breath. Give us children who will be the coolness of our eyes, who will carry our legacy, who will love their deen without us having to force it. And give life to the love between my wife and me — let it not become stale or functional. Let our love stay alive, evolving, growing deeper with every year."],
[61,"Al-Mumit","The Bringer of Death","Worldview & Consciousness","Death strips illusions of permanence. Live with urgency.","Ya Mumit, death is coming. I don’t know when, but it is coming. And when it arrives, it will not ask me about my Shopify revenue or my ad campaign ROAS. It will ask about my salah, my sincerity, my family, my heart. Let the awareness of death make me more urgent in my obedience and less attached to my possessions. Let it make me kinder to my wife, more patient with my parents, more present in my prayers, and more honest about what actually matters. I don’t want to die before becoming who I was supposed to become. Allahumma taqabbal. O Allah, accept this from me. You know what is in my heart better than I can articulate it. Accept the words I found and forgive the ones I couldn’t. Ameen."],
[62,"Al-Hayy","The Ever-Living","Akhirah","He will never die. You will. Build with purpose, not attachment.","Ya Hayy, You are alive and will never die, while I will die and leave everything behind — Sahara Delights, Hibachi Blue, every product I designed, every campaign I ran, every dollar I earned. Remind me of this reality every single day so that I build with purpose, not attachment. Let my work be sadaqah jariyah that outlives me. Let the brands I build feed people, employ people, and carry barakah long after I am gone. And when my life ends, let it end in a state that You love."],
[63,"Al-Qayyum","The Self-Subsisting","Character & Discipline","You are not the sustainer. He is.","Ya Qayyum, You sustain Yourself and everything else depends on You. I often try to sustain everything myself — my businesses, my family’s expectations, my own growth — and I burn out. Remind me that I am not the sustainer. I am the servant. You are the One who holds it all together. Let me work hard but depend on You completely. When I feel the weight of everything on my shoulders, remind me that You are carrying it and I am just doing my part."],
[64,"Al-Wajid","The Finder","Wealth & Provision","He finds the solution before you see the problem.","Ya Wajid, You find everything and lack nothing. Help me find what I need — the right suppliers, the right markets, the right price points, the right branding partners, the right commercial kitchen, the right opportunities for Sahara Delights to scale. When I feel stuck, when I can’t find the solution, when every path looks like a dead end — remind me that You are Al-Wajid and nothing is lost to You. Lead me to what I’m searching for."],
[65,"Al-Majid","The Illustrious","Dream Life & Legacy","An illustrious life is measured in sincerity, not followers.","Ya Majid, let my life tell an illustrious story — not one of fame, but one of substance. When my children and grandchildren look back at my life, let them see someone who built with integrity, worshipped with sincerity, loved with depth, and contributed something meaningful to the world. Let my legacy be illustrious in Your sight — not because of how many people knew my name, but because of how well I lived my purpose."],
[66,"Al-Wahid","The Unique","Marriage & Family","Let my family reflect something rare and intentional.","Ya Wahid, let our family be unique — not in a performative way, but in a way that reflects our values. Let our home be different from the homes of people who live on autopilot. Let our parenting be different from the disengaged norm. Let our marriage be different from the transactional model the world sells. Make our family a reflection of something rare — a household that worships You together, supports each other genuinely, and produces human beings who make the world better."],
[67,"Al-Ahad","The Indivisible","Deen & Sincerity","Stop serving multiple gods. Serve the One.","Ya Ahad, You are One and I want my life to point in one direction — toward You. I feel divided sometimes — pulled between building dunya and preparing for akhirah, between ambition and contentment, between what the world expects and what You require. Unify my purpose. Let every business I launch, every product I create, every dollar I earn, every word I speak serve one Master. Remove the division in my heart and make me singular in my devotion."],
[68,"As-Samad","The Self-Sufficient","Deen & Sincerity","Everything depends on Him. Turn to Him first.","Ya Samad, You need nothing from anyone while everything turns to You in need. Teach me to turn to You before I turn to strategies, before I turn to mentors, before I turn to Google. You are the One everything depends on. When I feel scattered across my businesses and responsibilities, let me depend on You first and let everything else follow. Make me someone who truly relies on You — not as a last resort, but as the first and only resort."],
[69,"Al-Qadir","The All-Powerful","Health & Fitness","He created galaxies. Don't limit your du'a.","Ya Qadir, You have power over everything, including the body I live in. If You can create galaxies, You can clear my skin, strengthen my frame, sharpen my mind, and give me the physique of someone who respects himself. I am asking You directly — give me a body that reflects self-discipline. Let my physical state match my inner ambitions. Remove what is draining my energy. Bless me with health that serves my worship, my work, and my family."],
[70,"Al-Muqtadir","The All-Determiner","Career & Building","The Determiner is not the algorithm.","Ya Muqtadir, You determine all outcomes. I plan campaigns, set budgets, build funnels, track KPIs — but You determine what converts and what doesn’t, what takes off and what stalls, who finds my brand and who scrolls past it. I submit to Your power over results. Don’t let me become obsessed with metrics to the point that I forget You are the One writing the outcome. Let my effort be excellent and my trust in You be total."],
[71,"Al-Muqaddim","The Expediter","Speech & Confidence","He puts the right words in your mouth at the right moment.","Ya Muqaddim, bring forward the words I need at the right time. When I’m in a conversation that matters — a negotiation, a difficult talk, a moment where I need to be clear and firm — put the right words in my mouth at the right moment. Don’t let me think of what I should have said after the conversation is over. Advance my communication ability ahead of schedule. I have ideas and vision in my head that deserve better articulation, and I’m asking You to close that gap. CHARACTER — DISCIPLINE, PATIENCE, HUMILITY & INNER STRENGTH"],
[72,"Al-Mu'akhkhir","The Delayer","Health & Fitness","Sometimes reflecting your own procrastination back at you.","Ya Mu’akhkhir, delay any illness, disease, or physical harm that is approaching me or my family. Push it back. Give me more healthy years to build, to worship, to raise children, to serve. And if I have been delaying my own health — putting off fitness, putting off better eating, putting off sleep discipline — then break that cycle. Don’t let me keep delaying the things my body needs. Let me prioritize my health now, before the delay becomes damage."],
[73,"Al-Awwal","The First","Health & Fitness","If health is the foundation, it must come first.","Ya Awwal, You are the First — before everything. Let me put my health first, before it becomes a crisis. Let me put my body first, before it breaks down from neglect. I know that health is the foundation everything else is built on — my business energy, my worship stamina, my emotional resilience, my ability to be present. Help me act on that knowledge. Make health the first thing I invest in each morning, not the thing I address after everything else falls apart. DREAM LIFE — BEAUTY, INTENTION, ENVIRONMENT & LEGACY"],
[74,"Al-Akhir","The Last","Akhirah","The only thing that matters is how you arrive at the endpoint.","Ya Akhir, You are the Last — the One who remains after every empire, every business, every generation, every universe has crumbled. When I feel pressure to rush, to compete, to prove myself now, remind me that You are the endpoint and nothing else matters except how I arrive at You. Calm my anxiety about timelines. I don’t need to have everything figured out at this age. I just need to be heading toward You."],
[75,"Adh-Dhahir","The Manifest","Career & Building","What is hidden will become manifest when He decides.","Ya Dhahir, make the work I do manifest in results I can see and share. I’ve been building behind the scenes — the fulfillment app, the Shopify infrastructure, the inventory systems, the branding, the recipes. Let it manifest now. Let the quiet years of grinding become visible in revenue, in recognition, in growth, and in impact. Let people see the fruit of what I’ve been planting. And let it be evident to me too — so I don’t lose heart before the harvest arrives."],
[76,"Al-Batin","The Hidden","Protection","He sees the hidden things inside you.","Ya Batin, You are the Hidden One who sees the hidden things inside me — the pride I haven’t addressed, the fears I haven’t named, the sins I haven’t fully repented from. Purify what is hidden in me. Remove the diseases of the heart that I don’t even know are there. Fix the parts of my character that I’m blind to. Let my inner world be as clean as the image I present to the outer world, because You see both — and on the Day of Judgment, only the inner one will matter."],
[77,"Al-Wali","The Patron","Protection","For the one juggling everything alone — He manages what you cannot.","Ya Wali, govern my affairs when they become too complex for me to manage alone — multiple businesses, family obligations, spiritual goals, health, and personal growth all at once. I don’t have a board of advisors or a management team. Most days it’s just me, trying to figure it all out. Be my patron. Direct my decisions. Manage what I cannot manage. And let me rest knowing that the One governing my life is the Lord of everything."],
[78,"Al-Muta'ali","Supremely Exalted","Dream Life & Legacy","Live above the things that pull you down.","Ya Muta’ali, lift me above the noise. Above the trends. Above the algorithms. Above the comparison. Above the cultural defaults that flatten people into consumers and content producers. I want a life that is exalted in quality, in intention, and in consciousness. I want to live awake — aware of what matters, resistant to what doesn’t, and devoted to building a life that honors You. Let me not be swept away by dominant norms just because they are dominant."],
[79,"Al-Barr","Source of Goodness","Forgiveness","When you want to be good — not just successful — you reflect Al-Barr.","Ya Barr, I want to be good — not just successful, not just impressive, not just productive — but genuinely good. Good in a way that my family feels, good in a way that my future children inherit, good in a way that is rooted in obedience to You. I ask You to make goodness easy for me, because sometimes it feels like the world rewards everything except genuine goodness. Fill me with Your goodness so deeply that it becomes who I am, not something I perform."],
[80,"At-Tawwab","Acceptor of Repentance","Forgiveness","He turns toward you before you turn toward Him.","Ya Tawwab, I turn to You again. I know I have turned to You before with the same flaws, the same bad habits, the same gaps between what I know and what I do. Accept my repentance even though I am not perfect in my return. Accept it even though I might stumble again. Every time I turn, turn toward me faster than I turned toward You. Let my tawbah be the kind that actually changes me — not just a momentary feeling, but a permanent redirection."],
[81,"Al-Muntaqim","The Avenger","Ummah & Justice","He avenges with perfect justice. His courtroom cannot be vetoed.","Ya Muntaqim, avenge the innocent. Avenge the children of Gaza. Avenge the mothers who lost everything. Avenge the men who were tortured. Avenge the families buried under rubble while the world debated whether they were worthy of sympathy. I don’t ask for vengeance from emotion — I ask because You are the Just Avenger, and there are people who have crossed every line. Let Your justice reach them in ways no human court ever could."],
[82,"Al-'Afuww","The Pardoner","Forgiveness","He doesn't just forgive — He erases. He loves to pardon.","Ya ‘Afuww, don’t just forgive — erase. Wipe it from the record as though it never happened. The nights I wasted, the prayers I missed, the opportunities I let slip because of fear or hesitation or overthinking — pardon them completely. You are the One the Prophet (peace be upon him) taught Aisha to call upon in the last ten nights of Ramadan. I call on You the same way: You love to pardon, so pardon me."],
[83,"Ar-Ra'uf","The Most Kind","Forgiveness","Extreme gentleness. Active, relentless kindness.","Ya Ra’uf, be kind to me in ways I don’t even know to ask for. Be kind to me in the tests I haven’t faced yet. Be kind to me in the consequences of mistakes I haven’t realized. Be kind to me in my marriage, in my health, in my business decisions, in my spiritual state. Your kindness is what prevents You from burdening me beyond my capacity — so be kind in what You place on my shoulders, and kind in how You help me carry it. DEEN — QURAN, SALAH, WORSHIP & SINCERITY"],
[84,"Malik ul-Mulk","Owner of Sovereignty","Dream Life & Legacy","He gives kingdom and takes it. The sovereignty is always borrowed.","Ya Malik ul-Mulk, You give kingdom to whom You will and You take it away. If You choose to give me influence, wealth, reach, and a platform — I accept it with responsibility. Use me. Let my success benefit the Ummah. Let my platform carry truth. Let the sovereignty You give me be a vehicle for good, not a trap for ego. And if You withhold it, I accept that too — because the sovereignty is Yours, and You distribute it by wisdom. UMMAH — PALESTINE, THE OPPRESSED & JUSTICE IN THE WORLD"],
[85,"Dhul Jalali wal Ikram","Lord of Majesty & Generosity","Marriage & Family","Both majesty and generosity. Commands respect and offers warmth.","Ya Dhul Jalali wal Ikram, bless my home with both majesty and generosity. Let our home be a place of beauty and dignity — not flashy, but intentional, warm, elegant, designed with taste. And let it be generous — open to guests, welcoming to family, a refuge for anyone who needs warmth. Let the home I build one day reflect who I am — thoughtful, premium, alive with barakah. Not random luxury. Thoughtful luxury. Beauty with meaning. Comfort with restraint."],
[86,"Al-Muqsit","The Equitable","Ummah & Justice","On Judgment Day, every atom of injustice will be corrected.","Ya Muqsit, You ensure perfect equity. On the Day of Judgment, no oppressor will escape. No dollar spent on bombs will go unaccounted. No propaganda lie will go uncorrected. Let that promise be a comfort to the oppressed and a warning to the oppressors. And let it be a reminder to me that I too will be asked about what I did with my comfort, my wealth, and my privilege while others suffered. Let me not be found wanting. Let me be among those who used what they had for good."],
[87,"Al-Jami'","The Gatherer","Marriage & Family","He gathers hearts and families.","Ya Jami’, gather my family together in goodness in this life and in Jannatul Firdaus in the next. Gather my parents, my wife, and my future children under Your mercy. Gather our hearts so we are not fragmented by busy schedules, devices, and distractions. And on the Day You gather all of humanity, gather us among the righteous — together, complete, and safe. HEALTH — PHYSICAL STRENGTH, FITNESS, ENERGY & APPEARANCE"],
[88,"Al-Ghaniyy","The Self-Sufficient","Wealth & Provision","Completely free of need yet He provides.","Ya Ghaniyy, You need nothing from me, yet You provide everything for me. Make me financially self-sufficient — not to hoard, but to be free. Free from depending on a paycheck I hate. Free from debt that keeps me up at night. Free from financial anxiety that clouds my creativity. Let my businesses generate enough to sustain my family and still have surplus to give. And keep me always aware that my sufficiency comes only from You."],
[89,"Al-Mughni","The Enricher","Wealth & Provision","He enriches in every dimension. True wealth is halal income plus inner contentment.","Ya Mughni, enrich me — not just in money but in contentment. I want halal wealth and I want the inner richness that makes me grateful whether I have abundance or tightness. Enrich my home with warmth. Enrich my marriage with depth. Enrich my mind with knowledge. Enrich my heart with closeness to You. And yes — enrich my bank account too, with income that flows from work I respect, products I’m proud of, and customers I genuinely serve."],
[90,"Al-Mani'","The Preventer","Protection","Sometimes His prevention is His greatest mercy.","Ya Mani’, sometimes Your withholding is Your greatest protection. If there is wealth that would corrupt me — prevent it. If there is a partnership that would destroy what I’ve built — block it. If there is success that would distance me from You — delay it until I’m ready to handle it. Prevent me from what would harm me, even when I want it badly, even when I can’t understand why the door won’t open. I trust that when You prevent, You protect."],
[91,"Ad-Darr","The Afflictor","Ummah & Justice","He creates hardship with wisdom. The Ummah's suffering is not in vain.","Ya Darr, You test through affliction — and the people of this Ummah are being tested beyond what the comfortable can imagine. Let their suffering not be in vain. Let it be purification, elevation, and a means to Jannah. And afflict the hearts of the heedless — including mine when I am heedless — with enough discomfort to wake them up. Don’t let me settle into a life of ease while forgetting the people who have no ease at all. WORLDVIEW — TRUTH, DEPTH, CONSCIOUSNESS & LIVING AWAKE"],
[92,"An-Nafi'","The Source of Good","Wealth & Provision","Every good thing that reaches you came from Him.","Ya Nafi’, let my work be a source of benefit to people. Let the dates I sell nourish bodies. Let the chai I serve bring people joy. Let the businesses I build create jobs, serve communities, and contribute something real. I don’t want empty success — I want my work to be beneficial in dunya and counted as good in akhirah. Let every transaction carry benefit, and let the ultimate benefit always flow back to You. MARRIAGE, FAMILY, HOME & CHILDREN"],
[93,"An-Nur","The Light","Deen & Sincerity","He illuminates hearts, paths, and destinies.","Ya Nur, illuminate my path when I can’t see where I’m going. My career path isn’t traditional — I’m not climbing a corporate ladder, I’m building from scratch in multiple directions. Light the way. Show me which venture to double down on and which to release. Put light in my heart so I can distinguish truth from trend, sincerity from ego, real opportunity from distraction. And put light in my face, in my speech, and in my home — the kind of light that only comes from closeness to You."],
[94,"Al-Hadi","The Guide","Deen & Sincerity","He guides through revelation, signs, and hearts.","Ya Hadi, guide me when I’m confused about what to do next. Guide my hands when I design. Guide my words when I pitch. Guide my decisions when I’m at a crossroads between what is profitable and what is right. I do not want to follow the crowd — I want to follow You. Guide me to the people, the knowledge, the opportunities, and the rizq that will bring me closer to You and closer to the life You want for me. And when I stray, guide me back before I go too far. PROTECTION — FROM NAFS, EGO, EVIL EYE & DISTRACTION"],
[95,"Al-Badi'","The Incomparable","Career & Building","He creates without precedent.","Ya Badi’, You create without precedent. Let my brands carry that same spirit of something never seen before. I don’t want Sahara Delights to be “just another date brand.” I don’t want Hibachi Blue to be “just another restaurant.” I want them to feel premium, intentional, and unlike anything else in the market. Bless me with the creative vision to make things that are incomparable — products, experiences, and brand stories that stand alone because they were built with purpose and precision. WEALTH — HALAL INCOME, PROVISION & FINANCIAL FREEDOM"],
[96,"Al-Baqi","The Everlasting","Akhirah","Everything you build will vanish. Only what was done for His sake will last.","Ya Baqi, everything I am building will one day vanish. The packaging I design, the logos, the menus, the products, the pop-up tents, the social media posts — all of it is temporary. Only what I did for Your sake will last. Make me someone who builds for dunya with excellence but builds for akhirah with obsession. Let the everlasting thing about my life be my deeds, not my brand."],
[97,"Al-Warith","The Inheritor","Akhirah","You are a steward, not an owner.","Ya Warith, You will inherit everything when all of creation has passed. Let me not cling to what was never mine. The businesses, the ideas, the wealth, the health — all of it is borrowed. Let me hold them with open hands and use them with sincerity. And when You take them back, let me not be someone who was so attached to the gift that he forgot the Giver. FORGIVENESS — FOR THE SINS I REMEMBER & THE ONES I FORGOT"],
[98,"Ar-Rasheed","The Right Guide","Protection","There is a right path. Walk it.","Ya Rasheed, keep me on the straight path when temptation pulls me sideways. Guide me right when I’m tempted to take shortcuts in business, when I’m tempted to water down my principles for profit, when I’m tempted to adopt practices that are sketchy or haram just because everyone else is doing them. I want to succeed — but not at the cost of my soul. Guide me to the version of success that You are pleased with. SPEECH — CLARITY, ELOQUENCE, CONFIDENCE & INFLUENCE"],
[99,"As-Sabur","The Most Patient","Character & Discipline","The One who created time is never in a rush. Why are you?","Ya Sabur, teach me patience — with my business growth, with my personal development, with my marriage, with my body, with my deen. I want results now and I get frustrated when progress is slow. But You are patient. You watch, You wait, You give chance after chance. Teach me to embody that same patience with myself and with others. Let me not rush the process, cut corners, or abandon something good just because it’s taking longer than I planned. CAREER — BUSINESS, BUILDING & MEANINGFUL WORK"],
];
export default function App(){
const[tab,sT]=useState("duas");
const[srch,sS]=useState("");
const[ss,sSS]=useState(false);
const[fv,sFv]=useState(new Set());
const[fo,sFo]=useState(false);
const[md,sMd]=useState(null);
const[rm,sRm]=useState(null);
const[fc,sFc]=useState(null);
const[eh,sEh]=useState(null);
const[col,sCol]=useState(new Set());
const[fcIdx,sFcIdx]=useState(0);
const[fcFlip,sFcFlip]=useState(false);
const rfs=useRef({});
const mk=useCallback((i)=>({id:D[i][0],n:D[i][1],m:D[i][2],cat:D[i][3],ex:D[i][4],du:D[i][5]}),[]);
const all=useMemo(()=>D.map((_,i)=>mk(i)),[mk]);
const tf=useCallback((id,e)=>{e.stopPropagation();sFv(p=>{const n=new Set(p);n.has(id)?n.delete(id):n.add(id);return n;});},[]);
const fl=useMemo(()=>{let d=all;if(srch){const q=srch.toLowerCase();d=d.filter(x=>x.n.toLowerCase().includes(q)||x.m.toLowerCase().includes(q)||x.du.toLowerCase().includes(q)||x.cat.toLowerCase().includes(q));}if(fo)d=d.filter(x=>fv.has(x.id));return d;},[srch,fo,fv,all]);
const gp=useMemo(()=>{const m={};CS.forEach(c=>{m[c]=[];});fl.forEach(d=>{if(m[d.cat])m[d.cat].push(d);});return m;},[fl]);
const scr=useCallback((c)=>{rfs.current[c]?.scrollIntoView({behavior:"smooth",block:"start"});},[]);
const rnd=useCallback(()=>all[Math.floor(Math.random()*all.length)],[all]);
const togCol=useCallback((c)=>{sCol(p=>{const n=new Set(p);n.has(c)?n.delete(c):n.add(c);return n;});},[]);
const HI=({f})=>(<svg width="16" height="16" viewBox="0 0 24 24" fill={f?G:"none"} stroke={G} strokeWidth="2"><path d="M20.84 4.61a5.5 5.5 0 0 0-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 0 0-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 0 0 0-7.78z"/></svg>);
const XI=()=>(<svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round"><path d="M18 6 6 18"/><path d="m6 6 12 12"/></svg>);
const bs={fontFamily:"Georgia,serif",background:BG,color:"#E8E2D6",minHeight:"100vh"};

if(fc){return(
<div style={{...bs,display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center",padding:32,textAlign:"center"}}>
<button onClick={()=>sFc(null)} style={{position:"fixed",top:16,right:16,background:"none",border:"none",color:Gd,cursor:"pointer",zIndex:10,padding:8}}><XI/></button>
<div style={{maxWidth:480,width:"100%"}}>
<div style={{fontSize:11,letterSpacing:3,textTransform:"uppercase",color:Gd,fontFamily:"Helvetica Neue,sans-serif",marginBottom:16}}>{fc.cat}</div>
<div style={{fontSize:22,color:G,marginTop:12}}>{"Yā "+fc.n}</div>
<div style={{fontSize:13,color:Gd,fontStyle:"italic",marginBottom:32,fontFamily:"Helvetica Neue,sans-serif",marginTop:4}}>{fc.m}</div>
<div style={{fontSize:17,lineHeight:2,color:"#C8C0B4",fontStyle:"italic",textAlign:"left"}}>{fc.du}</div>
</div>
<button onClick={()=>sFc(rnd())} style={{marginTop:40,background:"none",border:"1px solid "+BD,color:Gd,padding:"10px 24px",borderRadius:6,cursor:"pointer",fontSize:12,letterSpacing:2,fontFamily:"Helvetica Neue,sans-serif",textTransform:"uppercase"}}>Next</button>
</div>);}

const mcont=md||rm;
const mclose=()=>{sMd(null);sRm(null);};
return(
<div style={{...bs,position:"relative"}}>
<div style={{position:"fixed",inset:0,opacity:0.03,backgroundImage:"repeating-linear-gradient(0deg,transparent,transparent 40px,"+G+" 40px,"+G+" 41px),repeating-linear-gradient(90deg,transparent,transparent 40px,"+G+" 40px,"+G+" 41px)",pointerEvents:"none",zIndex:0}}/>
<div style={{position:"sticky",top:0,zIndex:50,background:"linear-gradient(180deg,"+BG+" 80%,transparent)",padding:"12px 16px 16px"}}>
<div style={{display:"flex",borderRadius:8,overflow:"hidden",border:"1px solid "+BD}}>
{["duas","names","heart"].map(t=>(<button key={t} onClick={()=>sT(t)} style={{flex:1,padding:"10px 0",background:tab===t?SF:"transparent",color:tab===t?G:Gd,border:"none",cursor:"pointer",fontSize:10,letterSpacing:2,fontFamily:"Helvetica Neue,sans-serif",textTransform:"uppercase",borderBottom:tab===t?"2px solid "+G:"2px solid transparent"}}>{t==="duas"?"Du'as":t==="names"?"99 Names":"My Heart"}</button>))}
</div>
{tab==="duas"&&ss&&(<div style={{display:"flex",alignItems:"center",gap:8,background:SF,borderRadius:8,padding:"8px 12px",border:"1px solid "+BD,marginTop:10}}>
<svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><circle cx="11" cy="11" r="8"/><path d="m21 21-4.35-4.35"/></svg>
<input autoFocus value={srch} onChange={e=>sS(e.target.value)} placeholder="Search..." style={{flex:1,background:"none",border:"none",color:"#E8E2D6",outline:"none",fontSize:14,fontFamily:"Helvetica Neue,sans-serif"}}/>
<button onClick={()=>{sS("");sSS(false);}} style={{background:"none",border:"none",color:Gd,cursor:"pointer",fontSize:18,padding:0}}>{"×"}</button>
</div>)}
</div>

{tab==="duas"&&(<div style={{position:"relative",zIndex:1}}>
{!srch&&!fo&&(<div style={{textAlign:"center",padding:"32px 24px 50px"}}>
<div style={{fontSize:14,color:Gd,fontStyle:"italic",letterSpacing:1,marginBottom:16}}>{"Bismillāhi r-Rahmāni r-Rahīm"}</div>
<div style={{fontSize:40,color:G}}>{"اللَّهُمَّ"}</div>
<div style={{fontSize:20,color:"#E8E2D6",letterSpacing:6,textTransform:"uppercase",fontFamily:"Helvetica Neue,sans-serif",fontWeight:300,marginTop:20}}>MY DU'AS</div>
<div style={{fontSize:11,color:Gd,letterSpacing:3,textTransform:"uppercase",fontFamily:"Helvetica Neue,sans-serif",marginTop:8,lineHeight:1.8}}>{"Through the 99 Names of Allah"}</div>
<div style={{width:60,height:1,background:G,margin:"24px auto",opacity:0.4}}/>
<div style={{fontSize:15,color:"#7A7368",fontStyle:"italic",lineHeight:1.8,maxWidth:360,margin:"0 auto"}}>{"These are not recitations from a book. These are the words of a soul that is trying — building, stumbling, asking, rising. Ameen."}</div>
</div>)}
<div style={{display:"flex",justifyContent:"center",gap:12,padding:"0 16px 20px"}}>
<button onClick={()=>sSS(!ss)} style={{background:"none",border:"1px solid "+BD,color:Gd,padding:"6px 14px",borderRadius:6,cursor:"pointer",fontSize:10,letterSpacing:2,fontFamily:"Helvetica Neue,sans-serif",textTransform:"uppercase"}}>Search</button>
<button onClick={()=>sFo(!fo)} style={{background:fo?SF:"none",border:"1px solid "+(fo?G:BD),color:fo?G:Gd,padding:"6px 14px",borderRadius:6,cursor:"pointer",fontSize:10,letterSpacing:2,fontFamily:"Helvetica Neue,sans-serif",textTransform:"uppercase"}}>Favorites</button>
</div>
{!srch&&!fo&&(<div style={{padding:"0 20px 24px"}}>{CS.map((c,i)=>(<div key={c} onClick={()=>scr(c)} style={{display:"flex",alignItems:"baseline",gap:8,padding:"7px 0",borderBottom:"1px solid "+BD,cursor:"pointer"}}><span style={{fontSize:11,color:Gd,fontFamily:"Helvetica Neue,sans-serif",minWidth:28}}>{String(i+1).padStart(2,"0")+"."}</span><span style={{fontSize:13,color:Gd,fontFamily:"Helvetica Neue,sans-serif"}}>{c}</span></div>))}</div>)}
<div style={{padding:"0 16px 120px"}}>{CS.map((cat,ci)=>{const items=gp[cat];if(!items||!items.length)return null;const isCol=col.has(cat);return(
<div key={cat} ref={el=>{rfs.current[cat]=el;}} style={{marginBottom:isCol?12:40,scrollMarginTop:80}}>
<div onClick={()=>togCol(cat)} style={{position:"sticky",top:68,zIndex:40,background:BG,borderLeft:"3px solid "+G,paddingLeft:16,paddingTop:12,paddingBottom:12,marginBottom:isCol?0:16,cursor:"pointer",display:"flex",justifyContent:"space-between",alignItems:"center",paddingRight:8}}>
<div><div style={{fontSize:10,letterSpacing:3,textTransform:"uppercase",color:Gd,fontFamily:"Helvetica Neue,sans-serif",marginBottom:2}}>{"Category "+String(ci+1).padStart(2,"0")}</div>
<div style={{fontSize:20,color:"#E8E2D6"}}>{cat}</div></div>
<div style={{display:"flex",alignItems:"center",gap:8}}><span style={{fontSize:11,color:Gd,fontFamily:"Helvetica Neue,sans-serif"}}>{items.length}</span><span style={{color:Gd,fontSize:14,transition:"transform 0.2s",transform:isCol?"rotate(0deg)":"rotate(180deg)"}}>{"▲"}</span></div>
</div>
{!isCol&&items.map(d=>(<div key={d.id} style={{borderLeft:"3px solid "+Gf,marginBottom:16,padding:"14px 14px 14px 18px",background:SF,borderRadius:"0 8px 8px 0"}}>
<div style={{display:"flex",alignItems:"flex-start",justifyContent:"space-between",gap:8,marginBottom:8}}>
<div><span style={{fontSize:11,color:Gd,fontFamily:"Helvetica Neue,sans-serif",marginRight:8,letterSpacing:1}}>{String(d.id).padStart(3,"0")}</span><span style={{fontSize:17,color:G,cursor:"pointer",textDecoration:"underline",textDecorationColor:Gf,textUnderlineOffset:3}} onClick={()=>sMd(d)}>{"Yā "+d.n}</span><div style={{fontSize:11,letterSpacing:2,textTransform:"uppercase",color:Gd,fontFamily:"Helvetica Neue,sans-serif",marginTop:3}}>{d.m}</div></div>
<button onClick={e=>tf(d.id,e)} style={{background:"none",border:"none",cursor:"pointer",padding:4,flexShrink:0}}><HI f={fv.has(d.id)}/></button></div>
<div style={{fontSize:15,lineHeight:1.95,color:"#B5AEA0",fontStyle:"italic"}}>{d.du}</div>
</div>))}
</div>);})}
{fl.length===0&&(<div style={{textAlign:"center",padding:40,color:Gd,fontStyle:"italic"}}>{fo?"No favorites yet":"No du'as match"}</div>)}
{!srch&&!fo&&fl.length>0&&(<div style={{textAlign:"center",padding:"40px 20px",background:SF,borderRadius:12,border:"1px solid "+BD}}>
<div style={{fontSize:28,color:G,marginBottom:20}}>{"اللَّهُمَّ آمِين"}</div>
<div style={{fontSize:14,color:Gd,fontStyle:"italic",lineHeight:2,maxWidth:360,margin:"0 auto"}}>{"These du'as were made with 99 names and one intention:"}<br/><br/><span style={{color:G}}>{"To return to You. Over and over again."}</span><br/><br/><em>{"Ameen."}</em></div>
</div>)}
</div></div>)}

{tab==="names"&&(<div style={{position:"relative",zIndex:1,padding:"16px 16px 120px"}}>
<div style={{textAlign:"center",marginBottom:24}}>
<div style={{fontSize:20,color:G,marginBottom:6}}>{"The 99 Names of Allah"}</div>
<div style={{fontSize:12,color:Gd,fontStyle:"italic"}}>{"Tap any name to learn more. Use flashcards to memorize."}</div>
<button onClick={()=>{sFcIdx(Math.floor(Math.random()*100));sFcFlip(false);sT("flash");}} style={{marginTop:12,background:"none",border:"1px solid "+G,color:G,padding:"8px 20px",borderRadius:6,cursor:"pointer",fontSize:11,letterSpacing:2,fontFamily:"Helvetica Neue,sans-serif",textTransform:"uppercase"}}>Flashcards</button>
</div>
{all.map(d=>(<div key={d.id} onClick={()=>sMd(d)} style={{display:"flex",alignItems:"center",gap:12,padding:"10px 14px",borderBottom:"1px solid "+BD,cursor:"pointer"}}>
<span style={{fontSize:11,color:Gd,fontFamily:"Helvetica Neue,sans-serif",minWidth:28}}>{String(d.id).padStart(3,"0")}</span>
<div style={{flex:1}}><div style={{fontSize:16,color:G}}>{"Yā "+d.n}</div><div style={{fontSize:11,color:Gd,letterSpacing:1,textTransform:"uppercase",fontFamily:"Helvetica Neue,sans-serif",marginTop:2}}>{d.m}</div></div>
<span style={{color:Gf,fontSize:12}}>{"›"}</span>
</div>))}
</div>)}

{tab==="flash"&&(<div style={{position:"relative",zIndex:1,padding:"20px 16px 120px",display:"flex",flexDirection:"column",alignItems:"center"}}>
<button onClick={()=>sT("names")} style={{alignSelf:"flex-start",background:"none",border:"none",color:Gd,cursor:"pointer",fontSize:12,fontFamily:"Helvetica Neue,sans-serif",marginBottom:16,padding:0}}>{"← Back to Names"}</button>
<div style={{fontSize:11,color:Gd,letterSpacing:2,fontFamily:"Helvetica Neue,sans-serif",textTransform:"uppercase",marginBottom:16}}>{(fcIdx+1)+" / 100"}</div>
<div onClick={()=>sFcFlip(!fcFlip)} style={{width:"100%",maxWidth:360,minHeight:320,background:SF,borderRadius:16,border:"1px solid "+(fcFlip?G:BD),display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"flex-start",padding:"40px 32px 32px",cursor:"pointer",transition:"border 0.3s"}}>
<div style={{fontSize:24,color:G,marginBottom:24,textAlign:"center"}}>{"Yā "+all[fcIdx].n}</div>
{!fcFlip?(<div style={{fontSize:12,color:Gd,fontStyle:"italic"}}>{"Tap to reveal meaning"}</div>):(<><div style={{fontSize:15,color:G,fontStyle:"italic",marginBottom:6,textAlign:"center"}}>{all[fcIdx].m}</div><div style={{width:40,height:1,background:Gf,margin:"10px auto 14px"}}></div><div style={{fontSize:13,lineHeight:1.8,color:"#B0A898",textAlign:"center",marginBottom:16}}>{all[fcIdx].ex}</div><div style={{fontSize:10,color:Gd,letterSpacing:2,textTransform:"uppercase",fontFamily:"Helvetica Neue,sans-serif",borderTop:"1px solid "+BD,paddingTop:12,marginTop:"auto",textAlign:"center"}}>{all[fcIdx].cat}</div></>)}
</div>
<div style={{display:"flex",gap:12,marginTop:20}}>
<button onClick={()=>{sFcIdx(p=>(p-1+100)%100);sFcFlip(false);}} style={{background:"none",border:"1px solid "+BD,color:Gd,padding:"10px 24px",borderRadius:8,cursor:"pointer",fontSize:12,fontFamily:"Helvetica Neue,sans-serif"}}>{"Previous"}</button>
<button onClick={()=>{sFcIdx(Math.floor(Math.random()*100));sFcFlip(false);}} style={{background:"none",border:"1px solid "+BD,color:Gd,padding:"10px 24px",borderRadius:8,cursor:"pointer",fontSize:12,fontFamily:"Helvetica Neue,sans-serif"}}>{"Shuffle"}</button>
<button onClick={()=>{sFcIdx(p=>(p+1)%100);sFcFlip(false);}} style={{background:"none",border:"1px solid "+BD,color:Gd,padding:"10px 24px",borderRadius:8,cursor:"pointer",fontSize:12,fontFamily:"Helvetica Neue,sans-serif"}}>{"Next"}</button>
</div>
</div>)}

{tab==="heart"&&(<div style={{position:"relative",zIndex:1,padding:"20px 16px 100px"}}>
<div style={{textAlign:"center",marginBottom:32,padding:"0 8px"}}>
<div style={{fontSize:22,color:G,marginBottom:12}}>{"What Lives in My Heart"}</div>
<div style={{width:40,height:1,background:G,margin:"0 auto 16px",opacity:0.4}}/>
<div style={{fontSize:14,color:"#8A8070",fontStyle:"italic",lineHeight:1.9,maxWidth:360,margin:"0 auto"}}>{"Before you read a single du'a, remember why you're reading it. These are the tensions, fears, desires, and hopes that live beneath every word. Return here to recenter your intention before you ask."}</div>
</div>
{HT.map((h,i)=>{const o=eh===i;return(
<div key={i} onClick={()=>sEh(o?null:i)} style={{borderLeft:"3px solid "+(o?G:Gf),background:o?SF:"transparent",borderRadius:"0 8px 8px 0",marginBottom:10,cursor:"pointer"}}>
<div style={{padding:"14px 16px 14px 20px",display:"flex",alignItems:"flex-start",justifyContent:"space-between"}}>
<div><span style={{fontSize:17,color:o?G:"#C8C0B4",display:"block"}}>{h.t}</span>{!o&&(<span style={{fontSize:12,color:Gf,fontStyle:"italic",marginTop:4,display:"block"}}>{h.q}</span>)}</div>
<span style={{color:Gd,fontSize:14,marginTop:4,transition:"transform 0.2s",transform:o?"rotate(45deg)":"none",flexShrink:0}}>{"+"}</span></div>
{o&&(<div style={{padding:"0 16px 18px 20px"}}>
<div style={{fontSize:13,color:G,fontStyle:"italic",marginBottom:12,fontFamily:"Helvetica Neue,sans-serif",letterSpacing:1}}>{h.q}</div>
<div style={{fontSize:15,lineHeight:1.95,color:"#A09888",fontStyle:"italic"}}>{h.c}</div>
</div>)}
</div>);})}
<div style={{textAlign:"center",marginTop:32,padding:"24px 16px",background:SF,borderRadius:12,border:"1px solid "+BD}}>
<div style={{fontSize:14,color:Gd,fontStyle:"italic",lineHeight:1.9,maxWidth:340,margin:"0 auto"}}>{"You want a life of depth, beauty, obedience, strength, truth, barakah, family, meaningful work, disciplined character, clear speech, halal wealth, protection from corruption, and nearness to Allah."}<br/><br/><span style={{color:G}}>{"That is the emotional backbone of every du'a in this collection."}</span></div>
</div>
</div>)}

<button onClick={()=>sRm(rnd())} style={{position:"fixed",bottom:24,right:20,width:52,height:52,borderRadius:"50%",background:"linear-gradient(135deg,#1A1610,#252015)",border:"1.5px solid "+G,color:G,cursor:"pointer",display:"flex",alignItems:"center",justifyContent:"center",zIndex:100,boxShadow:"0 4px 20px rgba(0,0,0,0.6),0 0 15px rgba(212,168,83,0.15)"}}>
<svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round"><polyline points="16 3 21 3 21 8"/><line x1="4" y1="20" x2="21" y2="3"/><polyline points="21 16 21 21 16 21"/><line x1="15" y1="15" x2="21" y2="21"/><line x1="4" y1="4" x2="9" y2="9"/></svg>
</button>

{mcont&&(<div onClick={mclose} style={{position:"fixed",inset:0,background:"rgba(0,0,0,0.88)",zIndex:200,display:"flex",alignItems:"center",justifyContent:"center",padding:16}}>
<div onClick={e=>e.stopPropagation()} style={{background:"#141210",borderRadius:14,padding:"28px 22px",maxWidth:440,width:"100%",maxHeight:"82vh",overflowY:"auto",border:"1px solid "+BD,position:"relative"}}>
<button onClick={mclose} style={{position:"absolute",top:12,right:12,background:"none",border:"none",color:Gd,cursor:"pointer"}}><XI/></button>
{rm?(<><div style={{fontSize:10,letterSpacing:2,textTransform:"uppercase",color:Gd,fontFamily:"Helvetica Neue,sans-serif",marginBottom:12}}>{mcont.cat}</div>
<div style={{fontSize:20,color:G}}>{"Yā "+mcont.n}</div>
<div style={{fontSize:12,color:Gd,marginTop:4,fontStyle:"italic"}}>{mcont.m}</div>
<div style={{width:40,height:1,background:Gd,margin:"16px 0",opacity:0.5}}/>
<div style={{fontSize:15,lineHeight:1.95,color:"#C8C0B4",fontStyle:"italic"}}>{mcont.du}</div>
<div style={{display:"flex",gap:8,marginTop:20}}>
<button onClick={()=>{mclose();sFc(mcont);}} style={{flex:1,background:"none",border:"1px solid "+BD,color:G,padding:"10px 0",borderRadius:8,cursor:"pointer",fontSize:12,fontFamily:"Helvetica Neue,sans-serif"}}>Focus Mode</button>
<button onClick={()=>sRm(rnd())} style={{flex:1,background:"none",border:"1px solid "+BD,color:G,padding:"10px 0",borderRadius:8,cursor:"pointer",fontSize:12,fontFamily:"Helvetica Neue,sans-serif"}}>Another</button>
</div></>):(<><div style={{textAlign:"center",marginBottom:16}}>
<div style={{fontSize:20,color:G}}>{"Yā "+mcont.n}</div>
<div style={{fontSize:12,color:Gd,marginTop:4,fontStyle:"italic"}}>{mcont.m}</div>
<div style={{fontSize:10,letterSpacing:2,textTransform:"uppercase",color:Gf,marginTop:8,fontFamily:"Helvetica Neue,sans-serif"}}>{mcont.cat}</div></div>
<div style={{width:40,height:1,background:Gd,margin:"0 auto 16px",opacity:0.5}}/>
<div style={{fontSize:10,letterSpacing:2,textTransform:"uppercase",color:Gd,marginBottom:10,fontFamily:"Helvetica Neue,sans-serif"}}>{"Understanding This Name"}</div>
<div style={{fontSize:15,lineHeight:1.9,color:"#B0A898",fontStyle:"italic"}}>{mcont.ex}</div>
<button onClick={()=>{mclose();sFc(mcont);}} style={{marginTop:16,width:"100%",background:"none",border:"1px solid "+BD,color:G,padding:"10px 0",borderRadius:8,cursor:"pointer",fontSize:12,fontFamily:"Helvetica Neue,sans-serif"}}>Focus Mode</button>
</>)}
</div></div>)}
</div>);
}
